# Generated by Django 5.0.2 on 2024-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_image_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('facebook', models.URLField()),
            ],
        ),
    ]
