# Generated by Django 5.0.2 on 2024-02-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
