# Generated by Django 5.0.2 on 2024-02-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_mobile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_phone',
        ),
    ]
