# Generated by Django 4.2.10 on 2024-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="donation_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
