# Generated by Django 4.2.10 on 2024-02-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_donation_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="donation_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
