# Generated by Django 4.2.10 on 2024-02-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_reportcomment"),
    ]

    operations = [
        migrations.RemoveField(model_name="reportcomment", name="project",),
    ]
