# Generated by Django 5.0.2 on 2024-02-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projectrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
