# Generated by Django 5.0.2 on 2024-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_category_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
